import { HCP, Interaction, Deviation, ProductComplaint, AdverseEvent, ProductRecall } from './types';

export const INITIAL_HCPS: HCP[] = [
  {
    id: 'hcp-101',
    name: 'Dr. Aris Thorne, MD',
    specialty: 'Cardiology & Electrophysiology',
    hospital: 'St. Jude Heart & Vascular Institute',
    city: 'Boston, MA',
    email: 'thorne.a@stjude-health.org',
    phone: '+1 (617) 555-0142',
    lastInteractionDate: '2026-09-10',
    preferredChannel: 'In-Person',
    complianceStatus: 'Approved',
    prescribingTier: 'Tier 1 (High)',
  },
  {
    id: 'hcp-102',
    name: 'Dr. Evelyn Vance, MD, PhD',
    specialty: 'Oncology & Immunotherapy',
    hospital: 'Memorial Sloan Cancer Center',
    city: 'New York, NY',
    email: 'evelyn.vance@mscc-research.org',
    phone: '+1 (212) 555-8839',
    lastInteractionDate: '2026-09-14',
    preferredChannel: 'Advisory Call',
    complianceStatus: 'Approved',
    prescribingTier: 'Tier 1 (High)',
  },
  {
    id: 'hcp-103',
    name: 'Dr. Marcus Bennett, DO',
    specialty: 'Endocrinology & Metabolic Disorders',
    hospital: 'Midwest Diabetes Care Clinic',
    city: 'Chicago, IL',
    email: 'm.bennett@midwestdiabetes.com',
    phone: '+1 (312) 555-4921',
    lastInteractionDate: '2026-08-28',
    preferredChannel: 'Virtual',
    complianceStatus: 'Approved',
    prescribingTier: 'Tier 2 (Moderate)',
  },
  {
    id: 'hcp-104',
    name: 'Dr. Sarah Lin, MD',
    specialty: 'Neurology & Movement Disorders',
    hospital: 'Pacific Rim Neuro Institute',
    city: 'San Francisco, CA',
    email: 'slin@pacificneuro.org',
    phone: '+1 (415) 555-9012',
    lastInteractionDate: '2026-09-02',
    preferredChannel: 'In-Person',
    complianceStatus: 'Pending Review',
    prescribingTier: 'Tier 2 (Moderate)',
  },
];

export const INITIAL_INTERACTIONS: Interaction[] = [
  {
    id: 'int-901',
    hcpId: 'hcp-101',
    hcpName: 'Dr. Aris Thorne, MD',
    specialty: 'Cardiology',
    date: '2026-09-10',
    type: 'In-Person Detail',
    productsDiscussed: ['Cardiogard ER 50mg', 'Vasodura IV'],
    keyNotes: 'Reviewed Phase III clinical safety endpoints for systolic hypertension patients. Dr. Thorne requested sample pack and monograph.',
    samplesProvided: [{ product: 'Cardiogard ER 50mg', quantity: 2 }],
    complianceCheck: {
      passed: true,
      flags: [],
      validatedBy: 'Compliance Guard v2.4 (Automated)',
      timestamp: '2026-09-10T14:32:00Z',
    },
    followUpRecommendation: 'Deliver requested clinical monograph on diastolic refill intervals within 14 days.',
    followUpDate: '2026-09-24',
    status: 'Audited',
  },
  {
    id: 'int-902',
    hcpId: 'hcp-102',
    hcpName: 'Dr. Evelyn Vance, MD, PhD',
    specialty: 'Oncology',
    date: '2026-09-14',
    type: 'Scientific Discussion',
    productsDiscussed: ['OncoVexil Monoclonal IgG1'],
    keyNotes: 'Dr. Vance inquired regarding off-label pediatric dosage protocols. Provided on-label safety summary and escalated investigator-initiated study form.',
    samplesProvided: [],
    complianceCheck: {
      passed: true,
      flags: ['Off-label inquiry handled via standard Medical Affairs MSL escalation protocol'],
      validatedBy: 'QA Officer Audit & Compliance Engine',
      timestamp: '2026-09-14T11:15:00Z',
    },
    followUpRecommendation: 'Ensure Medical Affairs specialist contacts Dr. Vance before Q4 advisory panel.',
    followUpDate: '2026-09-28',
    status: 'Submitted',
  },
];

export const INITIAL_DEVIATIONS: Deviation[] = [
  {
    id: 'DEV-2026-084',
    title: 'Autoclave sterilization temperature dip in Bioreactor Suite B',
    batchNumber: 'BT-8891-A',
    productName: 'Cardiogard ER Injectable Solution',
    detectedAt: '2026-09-15 08:30',
    detectedBy: 'P. Atrishi (Production Tech)',
    department: 'Production',
    severity: 'Major',
    stage: 'Root Cause Analysis',
    description: 'During 121°C sterilization cycle, secondary sensor registered a 1.8°C thermal excursion for 4 minutes due to valve pressure fluctuation.',
    rootCause: 'Steam pressure regulator diaphragm wear led to transient inlet vacuum.',
    capaAction: 'Replace steam diaphragm regulator across lines 3 & 4; re-validate autoclave cycle with 12-point thermocouple mapping.',
    assignedRole: 'PRODUCTION_MANAGER',
  },
  {
    id: 'DEV-2026-079',
    title: 'Secondary packaging foil seal misalignment on blister cards',
    batchNumber: 'BL-4412-K',
    productName: 'OncoVexil Oral 20mg',
    detectedAt: '2026-09-11 14:15',
    detectedBy: 'S. Patel (QA Inspector)',
    department: 'Packaging',
    severity: 'Minor',
    stage: 'Action Planned',
    description: 'Optical inspection system rejected 42 units out of 10,000 for 1.2mm foil offset.',
    rootCause: 'Optical feeder guide rail vibration loosening during high-speed feeder switchover.',
    capaAction: 'Installed pneumatic lock dampers on guide rail bracket. Daily torque verification added to shift checklist.',
    assignedRole: 'QA_OFFICER',
  },
  {
    id: 'DEV-2026-068',
    title: 'Cold storage unit #4 temperature logger excursion (+7.4°C)',
    batchNumber: 'CS-1090-X',
    productName: 'Vasodura IV Cold Concentrate',
    detectedAt: '2026-09-03 04:10',
    detectedBy: 'Automated BMS Sensor',
    department: 'Storage/Cold Chain',
    severity: 'Critical',
    stage: 'Verified',
    description: 'Sensor recorded +7.4°C for 38 minutes (spec limit 2-8°C, alarm threshold was set at +7.0°C). Product quarantine initiated immediately.',
    rootCause: 'Backup compressor transfer switch delayed engagement during municipal power brownout.',
    capaAction: 'Replaced automatic transfer relay; accelerated secondary backup generator test schedule.',
    verificationNotes: 'Product stability testing confirmed all 400 quarantined vials remained within bio-equivalence parameters. QA release authorized with stability endorsement.',
    assignedRole: 'QA_OFFICER',
  },
];

export const INITIAL_COMPLAINTS: ProductComplaint[] = [
  {
    id: 'CMP-2026-104',
    complaintNumber: 'CMP-104-09',
    reportedBy: 'Dr. Evelyn Vance, MD',
    reporterType: 'HCP',
    product: 'OncoVexil Monoclonal IgG1',
    batchNumber: 'BT-8720-C',
    dateReported: '2026-09-12',
    category: 'Packaging Defect',
    status: 'CAPA Initiated',
    resolutionSummary: 'Vial crimp seal rubber stopper showed hairline micro-crimp during hospital preparation.',
  },
  {
    id: 'CMP-2026-098',
    complaintNumber: 'CMP-098-08',
    reportedBy: 'Metropolitan Hospital Central Pharmacy',
    reporterType: 'Distributor',
    product: 'Cardiogard ER 50mg',
    batchNumber: 'BL-4390-E',
    dateReported: '2026-08-30',
    category: 'Labeling',
    status: 'Resolved',
    resolutionSummary: 'Expiration date printing contrast was faint under barcode scanner; batch overprint verified and scanner contrast threshold updated.',
  },
];

export const INITIAL_ADVERSE_EVENTS: AdverseEvent[] = [
  {
    id: 'AE-2026-019',
    caseId: 'MDR-US-2026-8819',
    patientInitials: 'J.D.',
    hcpReporter: 'Dr. Aris Thorne, MD',
    suspectDrug: 'Cardiogard ER 50mg',
    reactionDescription: 'Transient symptomatic bradycardia (pulse 42 bpm) 90 minutes post first dose in patient taking concomitant beta-blocker.',
    reportedDate: '2026-09-11',
    seriousnessCriteria: 'Medically Significant',
    fdaMdrStatus: 'Transmitted',
  },
  {
    id: 'AE-2026-018',
    caseId: 'MDR-US-2026-7910',
    patientInitials: 'R.M.',
    hcpReporter: 'Dr. Sarah Lin, MD',
    suspectDrug: 'NeuroZen XR 10mg',
    reactionDescription: 'Severe urticaria and facial flushing 30 minutes post infusion.',
    reportedDate: '2026-09-04',
    seriousnessCriteria: 'Hospitalization',
    fdaMdrStatus: 'Acknowledged',
  },
];

export const INITIAL_RECALLS: ProductRecall[] = [
  {
    id: 'RCL-2026-003',
    recallCode: 'FDA-RCL-26-003',
    productName: 'Vasodura IV 100ml Infusion Bags',
    affectedBatches: ['VB-2026-11A', 'VB-2026-11B'],
    classification: 'Class II',
    initiationDate: '2026-08-15',
    status: 'Quarantine Secured',
    recoveryRatePercent: 94.6,
    regulatoryNotified: true,
  },
];
